import { X, LucideIcon } from 'lucide-react';

interface VCCriteriaModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  score: number;
  feedback: string;
  icon: LucideIcon;
  color: string;
}

export function VCCriteriaModal({ isOpen, onClose, title, score, feedback, icon: Icon, color }: VCCriteriaModalProps) {
  if (!isOpen) return null;

  const getScoreColor = (score: number) => {
    if (score >= 7) return 'text-green-600';
    if (score >= 5) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreLabel = (score: number) => {
    if (score >= 8) return 'Excellent';
    if (score >= 7) return 'Good';
    if (score >= 5) return 'Fair';
    if (score >= 3) return 'Weak';
    return 'Critical';
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm">
      <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto bg-white rounded-2xl shadow-2xl">
        <div className="sticky top-0 z-10 bg-white border-b border-slate-200 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg bg-slate-100 ${color}`}>
              <Icon className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-900">{title}</h2>
              <div className="flex items-center gap-2 mt-1">
                <span className={`text-2xl font-bold ${getScoreColor(score)}`}>
                  {score.toFixed(1)}/10
                </span>
                <span className={`text-sm font-semibold px-2 py-1 rounded ${
                  score >= 7 ? 'bg-green-100 text-green-700' :
                  score >= 5 ? 'bg-yellow-100 text-yellow-700' :
                  'bg-red-100 text-red-700'
                }`}>
                  {getScoreLabel(score)}
                </span>
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-slate-600" />
          </button>
        </div>

        <div className="p-6">
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-bold text-slate-900 mb-2">Score Interpretation</h3>
              <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-medium text-slate-600">Score Range:</span>
                  <span className={`text-sm font-bold ${getScoreColor(score)}`}>
                    {score >= 8 ? '80-100: Excellent' :
                     score >= 7 ? '70-79: Good' :
                     score >= 5 ? '50-69: Fair' :
                     score >= 3 ? '30-49: Weak' :
                     '0-29: Critical'}
                  </span>
                </div>
                <div className="w-full h-2 bg-slate-200 rounded-full overflow-hidden">
                  <div
                    className={`h-full transition-all duration-500 ${
                      score >= 7 ? 'bg-green-500' :
                      score >= 5 ? 'bg-yellow-500' :
                      'bg-red-500'
                    }`}
                    style={{ width: `${score * 10}%` }}
                  />
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-bold text-slate-900 mb-3">Comprehensive Assessment</h3>
              <div className="bg-white border border-slate-200 rounded-lg p-5">
                <div className="text-slate-700 text-base leading-relaxed space-y-3">
                  {feedback ? (
                    feedback.split(/\.\s+/).filter(s => s.trim()).map((sentence, idx) => (
                      <p key={idx} className="text-slate-700">
                        {sentence.trim()}{sentence.trim().endsWith('.') ? '' : '.'}
                      </p>
                    ))
                  ) : (
                    <p className="text-slate-500 italic">No detailed feedback available for this criterion.</p>
                  )}
                </div>
              </div>
            </div>

            <div className="pt-4 border-t border-slate-200">
              <p className="text-xs text-slate-500 italic">
                This assessment is generated by AI analysis of your pitch deck content and represents typical VC evaluation criteria.
                Consider this as initial feedback to improve your deck before approaching investors.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
