/*
  # Add Detailed Metric Feedback

  1. Changes
    - Add `word_density_feedback` column to analyses table
      - Stores detailed explanation of the word density assessment
    - Add `disruption_signal_feedback` column to analyses table
      - Stores detailed explanation of the disruption signal score
    - Add `page_count_feedback` column to analyses table
      - Stores detailed explanation of the page count assessment
  
  2. Notes
    - These fields will provide detailed context when users click on metric cards
    - Generated by OpenAI during the analysis process
*/

DO $$
BEGIN
  -- Add word_density_feedback column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'analyses' AND column_name = 'word_density_feedback'
  ) THEN
    ALTER TABLE analyses ADD COLUMN word_density_feedback text DEFAULT NULL;
  END IF;

  -- Add disruption_signal_feedback column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'analyses' AND column_name = 'disruption_signal_feedback'
  ) THEN
    ALTER TABLE analyses ADD COLUMN disruption_signal_feedback text DEFAULT NULL;
  END IF;

  -- Add page_count_feedback column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'analyses' AND column_name = 'page_count_feedback'
  ) THEN
    ALTER TABLE analyses ADD COLUMN page_count_feedback text DEFAULT NULL;
  END IF;
END $$;